<?php
/**
 * Created by PhpStorm.
 * User: fruit
 * Date: 11/27/2018
 * Time: 12:12 AM
 */

namespace App\Http\Controllers;


use App\BusinessCard;
use Illuminate\Http\Request;

class BusinessCardController extends Controller
{
    protected $bcard;

    public function __construct(BusinessCard $card)
    {
        parent::__construct($card, []);
        $this->bcard = $card;
    }
    public function getAll()
    {
        return $this->bcard::where('deleted_by', null)->get(); // TODO: Change the autogenerated stub
    }

    public function getByUser(Request $request, $user_id) {
        return $this->bcard::where('deleted_by', null)->where(function ($where) use ($user_id){
            $where->whereHas('permissions', function($query) use ($user_id) {
                $query->where('user_id', $user_id);
                $query->whereHas('permission', function ($q) {
                    $q->where('name', 'Read');
                });
            })->orWhere('private', false)->orWhere('created_by', $user_id);
        })->with('permissions.permission')->orderBy('created_at', 'desc')->get();
    }

    public function delete(Request $request, $id)
    {
        $result = $this->bcard::findOrFail($id)
                    ->fill(['deleted_by' => $request->input('user_id')])->save();
        return response()->json($result);
    }
}