<?php

namespace App\Http\Controllers;


use App\BusinessCard;
use Illuminate\Http\Request;

class BusinessCardController extends Controller
{
    protected $business_card;
    protected $rules = [];

    public function __construct(BusinessCard $card)
    {
        parent::__construct($card, $this->rules);
        $this->business_card = $card;
    }

    public function getByUser(Request $request, $user_id) {
        return $this->business_card::with(['permissions.permission','permissions.user'])->orderBy('created_at', 'desc')->get();
    }
    public function add(Request $request)
    {
        if ($request->file('photo')) {
            $photo = $request->file('photo');
            $name = time().'.'.$photo->extension();
            $photo->move('images/',$name);
            $request['image_path'] = 'images/'.$name;
        }
        return parent::add($request);// TODO: Change the autogenerated stub
    }

}